# Generated by Django 6.0.4 on 2026-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('uzMade', 'Uz Made'), ('startups', 'Startups'), ('social', 'Social'), ('scientific', 'Scientific')], default='uzMade', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('tag', models.CharField(max_length=100)),
                ('desc', models.TextField(help_text='Short description for the list view')),
                ('full_desc', models.TextField(blank=True, help_text='Full description for the detail page', null=True)),
                ('expected_results', models.TextField(blank=True, null=True)),
                ('youtube_id', models.CharField(blank=True, help_text='e.g. SmPNYkjfGbY', max_length=50, null=True)),
            ],
        ),
    ]
