# Generated by Django 6.0.4 on 2026-04-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Paste YouTube link or ID here', max_length=255, null=True),
        ),
    ]
