# Generated by Django 6.0.4 on 2026-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Events', 'Events'), ('Grants', 'Grants'), ('Partnerships', 'Partnerships')], default='Events', max_length=100),
        ),
    ]
